# config.py

# Telegram Bot Configuration
BOT_TOKEN = "7887959083:AAElm33V2ojKEY1giilQs5OCDlpPd_RiZlA"
TELEGRAM_USER_ID = 7190856352

# MEXC API Credentials
MEXC_API_KEY = "mx0vglietIzr9GgA01"
MEXC_SECRET_KEY = "06933d9ba4ce499682cb9823224defd0"

# Symbols to Monitor
SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT",
    "TONUSDT", "SUIUSDT", "PEPEUSDT", "LINKUSDT", "FLOKIUSDT",
    "BONKUSDT", "JUPUSDT", "ADAUSDT", "AVAXUSDT", "SHIBUSDT",
    "VIRTUALUSDT", "FARTCOINUSDT", "MOODENGUSDT", "BOMEUSDT",
    "DEGENUSDT", "MAJORUSDT", "XEMPIREUSDT", "DOGSUSDT"
]

# Timeframes for Analysis
TIMEFRAMES = ["15m", "1h", "4h"]
